# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb15c936e76d3582cd4d9f06a2ab01f85c93003c2f548a62ed167f2284204e5f0bdb5cbb2d39e20e2ef16193c87501af4445d60c36f5b3d16ea80e2823fd310

test:
  secret_key_base: e4deb736c1ab0bb4e2b7dbcef5ec0df6c7f34d4e69500b90e7bca417be248c901b1293b632457adb4f146ed983c6b5b4e0508f356d7bc50f0a44ee93615abe3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
